builds:
  -
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
        - -s -w -X github.com/zx06/ddnss/build.Version={{.Version}} -X github.com/zx06/ddnss/build.Commit={{.ShortCommit}} -X github.com/zx06/ddnss/build.BuildDate={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip